### PR TITLE
Introduce ESLint checker.

### PR DESCRIPTION
**Pull request by jmuk**
Note: this causes *lots* of style errors but this does not
address any of those style violations. This is simply the
introduction of style checker, so that anybody can see what's
wrong / what should be fixed later.

### CODE REVIEW

**Comment by karino2** [comment]
Could you tell me how to confirm?
I try npm install jslint, then call node jslint.js editors/monaco/editbook_main.js
The result is

```
 #1 'document' was used before it was defined.
    document.body.style.margin = '0'; // Line 7, Pos 5
 #2 'MonacoMenu' was used before it was defined.
    var menu = new MonacoMenu(elem); // Line 8, Pos 20
 #3 Combine this with the previous 'var' statement.
    var main_editor =  new EditBookMonacoEditor(menu.main_div); // Line 10, Pos 9
 #4 'EditBookMonacoEditor' was used before it was defined.
    var main_editor =  new EditBookMonacoEditor(menu.main_div); // Line 10, Pos 28
 #5 Combine this with the previous 'var' statement.
    var sub_editor = new EditBookMonacoEditor(menu.sub_div); // Line 11, Pos 9
 #6 'EditBookMonacoEditor' was used before it was defined.
    var sub_editor = new EditBookMonacoEditor(menu.sub_div); // Line 11, Pos 26
 #7 Combine this with the previous 'var' statement.
    var onInit = InitializeModule(); // Line 13, Pos 9
 #8 'InitializeModule' was used before it was defined.
    var onInit = InitializeModule(); // Line 13, Pos 18
 #9 Unexpected ')'.
    onInit.push(() => { main_editor.init(); }); // Line 14, Pos 18
#10 Stopping. (5% scanned).
     // Line 14, Pos 20
```

Is this correct?

**Comment by jmuk** [comment]
It seems not. This introduces **ES**lint, not js (see http://eslint.org/). With this pR, you can run this as:
```sh
% npm update
% npm run lint
```

**Comment by karino2** [comment]
Thanks. I see. The result is looks like:

```
> @ lint D:\go\src\github.com\karino2\editbook\editors\monaco
> eslint *.js


D:\go\src\github.com\karino2\editbook\editors\monaco\editbook_main.js
    1:14   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                linebreak-style
    2:1    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                linebreak-style
    3:1    error  Unexpected var, use let or const instead                                                                       no-var
    3:5    error  Identifier 'g_current' is not in camel case                                                                    camelcase
    3:15   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                linebreak-style
    4:1    error  Unexpected var, use let or const instead                                                                       no-var
    4:5    error  Identifier 'g_menu' is not in camel case                                                                       camelcase
    4:12   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                linebreak-style
    5:1    error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                linebreak-style
    6:1    error  Missing JSDoc comment                                 
...
```

**Comment by karino2** [comment]
I guess we need to consider rule more carefully, but we can do it later.
So I merge this PR now.

**Comment by jmuk** [comment]
CRLF / LF thing is not happening on my environment. It is possibly because you ran it on a Windows machine where git checkout converts linebreaks?

Probably, adding
```yaml
rules:
  linebreak-style: off
```

to `editors/monaco/.eslintrc.yml` will remove those errors (see http://eslint.org/docs/rules/linebreak-style and http://eslint.org/docs/user-guide/configuring#configuring-rules)

**Comment by karino2** [comment]
Agree.
But the point is, should we do those kind of works now, or later?
Most correct reaction to this issue  would be check each rule and decide which rule we should follow.
I feel line break style is just one of them. 

May be it's enough to just turn off line break style check and leave other  style errors as-is, but I'm not sure about other style errors.

Any suggestion?

**Pull request merged**
